console.log("salida de mi casa");
console.log("camino por calle san juan hasta llegar a AV alsina");
console.log("giro a la deracha");
console.log("Camino por AV alsina hasta calle Rivadava");
console.log("giro a la izquierda");
console.log("camino por calle rivadavia hasta llegar a AV zabalsa");
console.log("cruzo AV zabalsa");
console.log("ingreso al supermercado");
console.log("realizo compras");
console.log("realizo mismo camino a la inversa hasta llegar a casa");
console.log("ingreso a casa");
